services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: unless-stopped

    env_file:
      - .env

    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    expose:
      - "8000"

    command:
      - gunicorn
      - sole.wsgi:application
      - --bind=0.0.0.0:8000
      - --workers=2
      - --timeout=120

    labels:
      - traefik.enable=true
      - traefik.http.routers.sole.rule=Host(`ec2-52-66-205-58.ap-south-1.compute.amazonaws.com`)
      - traefik.http.routers.sole.entrypoints=websecure
      - traefik.http.routers.sole.tls.certresolver=letsencrypt
      - traefik.http.services.sole.loadbalancer.server.port=8000

    networks:
      - spider

  celery:
    build: .
    restart: unless-stopped

    env_file:
      - .env

    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    command:
      - celery
      - -A
      - sole
      - worker
      - --loglevel=info
      - --concurrency=2

networks:
  spider:
    external: true